version: "2.1"
x-logger: &logger
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
x-common: &common
  image: jd-scripts:latest
  build:
    context: .
    dockerfile: ./Dockerfile
  restart: always

services:
  jd1:
    <<: [ *logger, *common ]
    container_name: jd1
    environment:
      - JD_COOKIE=
  jd2:
    <<: [ *logger, *common ]
    container_name: jd2
    environment:
      - JD_COOKIE=
